version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: EventApi(!)
      ExternalEventCatalogBaseUrl: http://localhost:7100
    ports:
      - "7100:80"
    container_name: eventscatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment: 
       ACCEPT_EULA: Y
       SA_PASSWORD: EventApi(!)
    ports:
       - "1450:1433"
    container_name: eventssqlserver
    networks:
       - backend

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: event/tokenapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5300
    ports:
      - "6750:80"
    container_name: eventtokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  webmvc:
    build:
      context: .\WebMVC
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: eventshop
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventUrl: http://catalog
      IdentityUrl: http://192.168.86.42:6750
      CallBackUrl: http://localhost:5300
    ports:
      - "5300:80"
    networks:
      - frontend
    depends_on:
      - catalog