version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: events/catalogapi
    build:
      context: .\EventCatalogApi
      dockerfile: Dockerfile
    environment:
      DatabaseServer: mssqlserver
      DatabaseName: EventDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
      ExternalEventCatalogBaseUrl: http://localhost:7100
    ports:
      - "7100:80"
    container_name: eventscatalogapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  cart:
    build:
      context: .\CartApi
      dockerfile: Dockerfile
    image: events/cartapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.14:6750
      ConnectionString: basket.data
    ports:
      - "6900:80"
    container_name: eventcartapi
    networks:
      - backend
      - frontend
    depends_on:
      - basket.data
      - tokenserver
      

  order:
    build:
      context: .\OrderApi
      dockerfile: Dockerfile
    image: events/orderapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      IdentityUrl: http://192.168.0.14:6750
      DatabaseServer: mssqlserver
      DatabaseName: OrdersDb
      DatabaseUser: sa
      DatabasePassword: ProductApi(!)
    ports:
      - "7200:80"
    container_name: eventorderapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver
      - tokenserver
      


  mssqlserver:
    image: "microsoft/mssql-server-linux:latest"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ProductApi(!)
    ports:
      - "1450:1433"
    container_name: eventssqlserver
    networks:
      - backend

  tokenserver:
    build:
      context: .\TokenServiceApi
      dockerfile: Dockerfile
    image: events/tokenapi
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MvcClient: http://localhost:5300
      BasketApiClient: https://localhost:6900
    ports:
      - "6750:80"
    container_name: eventtokenserviceapi
    networks:
      - backend
      - frontend
    depends_on:
      - mssqlserver

  WebMVC:
    build: 
      context: .\WebMVC
      dockerfile: Dockerfile
    image: events/webmvc
    container_name: eventshop
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      EventUrl: http://catalog
      IdentityUrl: http://192.168.0.14:6750
      CallBackUrl: http://localhost:5300
      CartUrl: http://cart
      OrderUrl: http://order
      StripePublicKey: pk_test_7nZPrFh762JFGjOtYAw19ZIt00gMAgyOxb
      StripePrivateKey: sk_test_9Ypz3RsMvvLNunf7jk9t3xb900nZJUEwjX
    ports:
      - "5300:80"
    networks:
      - frontend
    depends_on:
      - catalog
      - cart
      - order
      - tokenserver

  basket.data:
    image: redis
    container_name: eventbasketdata
    ports:
      - "6200:6379"
    networks:
      - backend

 